### PR TITLE
Bump requirements.

### PR DESCRIPTION
**Pull request by adam-thomas**
Don't bump flake8-import-order since it is borked.

@incuna/backend merge please? :)

### CODE REVIEW

**Comment by kevinetienne** [comment]
I don't see the link for the travis test, is this normal?

**Comment by adam-thomas** [comment]
Yeah this project doesn't have Travis or any tests, it's just a base we can build other projects off. :)

**Comment by adam-thomas** [comment]
Added coverage 4.0.3 as well, that one's actually important.  Oops :P

**Comment by adam-thomas** [comment]
Thanks :)

**Pull request merged**
